apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- argocd

secretGenerator:
- name: argocd-server-tls
  options:
    disableNameSuffixHash: true
  files:
  - certificates/tls.crt
  - certificates/tls.key
  type: "kubernetes.io/tls"
  namespace: argocd
- name: nginx-tls
  options:
    disableNameSuffixHash: true
  files:
  - certificates/tls.crt
  - certificates/tls.key
  type: "kubernetes.io/tls"
  namespace: ingress-nginx
