apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- github.com/argoproj/argo-cd/manifests/crds?ref=v2.7.6
- github.com/argoproj/argo-cd/manifests/ha/base?ref=v2.7.6
- ingress.yaml

patches:
- path: argocd-secret.patch.yaml
- path: argocd-cm.patch.yaml
#- path: argocd-rbac-cm.patch.yaml

